version: "3"

services:
  app:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/Users/tom/Documents/Jenkins:/var/jenkins_home"
      
      # -e "DOCKER_GID_ON_HOST=$(cat /etc/group | grep docker: | cut -d: -f3)" oose/dockerjenkins
    networks:
      - jenkinsnet
networks:
  jenkinsnet:
